version: "3.8"

services:
    kokunime:
        container_name: web
        build:
            context: .
            dockerfile: ./dockerfiles/production/Dockerfile
        image: kokunime:latest
        restart: always
        ports:
            - 3000:3000
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M
