import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { ChildrenProps } from "@/interfaces";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import "./globals.css";
import Loading from "./loading";

export const metadata = {
  title: "Kokunime",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: ChildrenProps): JSX.Element => (
  <html lang="en" className="scroll-smooth">
    <body
      suppressHydrationWarning
      className="!overflow-x-hidden bg-gradient-to-tl from-slate-900 via-slate-800 to-slate-900 min-h-screen flex flex-col justify-between"
    >
      <NextTopLoader showSpinner={false} />
      <Suspense fallback={<Loading />}>
        <Navbar />
        <main className="flex-auto">{children}</main>
        <Footer />
      </Suspense>
    </body>
  </html>
);

export default RootLayout;
